spring.application.name=Revisao_Para_Prova
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/revisaopv
spring.datasource.username=root
spring.datasource.password=